services:

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "3000:3000"

    restart: on-failure
    depends_on:
      - user
      - captain
      - ride
    networks:
      - ride-network

  user:
    build: ./user
    container_name: user
    ports:
      - "3001:3001"

    restart: on-failure
    networks:
      - ride-network

  captain:
    build: ./captain
    container_name: captain
    ports:
      - "3002:3002"

    restart: on-failure
    networks:
      - ride-network

  ride:
    build: ./ride
    container_name: ride
    ports:
      - "3003:3003"

    restart: on-failure
    networks:
      - ride-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: on-failure
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - ride-network

networks:
  ride-network:

volumes:
  rabbitmq-data: